export const en: Record<string, string> = {
  // Nav
  nav_home: "Home",
  nav_projects: "Projects",
  nav_analysis: "Insights",

  // Hero
  name: "Frank Fan",
  role_zh: "IT Project Manager / PMP",
  role_en: "IT Project Manager / PMP",
  hero_intro: "Senior IT Project Delivery Manager with 5+ years of experience in system integration and digital transformation. PMP certified. Focused on enterprise iPaaS, ECM, and big data project delivery with full lifecycle management and cross-department coordination. Managed projects with budgets exceeding 10M RMB, leading teams of 10-20 to deliver multiple state-owned enterprise and multinational projects.",
  email: "frank@hk-it.hk",
  twitter: "@frank4938",
  weixin: "A493832816",

  // Counters
  years_experience: "Years IT Experience",
  projects_count: "Core Projects",
  max_budget: "10M+ Max Budget",
  team_size: "Team Size",

  // Skills
  skills: "Professional Skills",
  skills_ai: "AI Capabilities",
  skills_backend: "Backend & Middleware",
  skills_data: "Data & Operations",
  radar_pm: "Project Mgmt",
  radar_req: "Requirements",
  radar_arch: "Tech Architecture",
  radar_lead: "Team Leadership",
  radar_risk: "Risk Control",
  radar_cross: "Cross-dept Coord",

  // Skill items
  skill_ai_llm: "AI/LLM Fundamentals",
  skill_ai_poc: "AI Requirement Assessment & POC",
  skill_ai_prompt: "Prompt Engineering",
  skill_ai_design: "AI Integration Design",
  skill_java: "Java EE / Spring Boot",
  skill_esql: "ESQL / IBM MQ (RDQM)",
  skill_ace: "IBM ACE / Apache NiFi",
  skill_apiconnect: "IBM API Connect",
  skill_oracle: "Oracle / PostgreSQL / DB2",
  skill_sqlserver: "SQL Server / Redis",
  skill_elk: "ELK + Jaeger",
  skill_prometheus: "Prometheus + Grafana",
  skill_docker: "Docker / Jenkins",

  // Work experience
  work_experience: "Work Experience",
  work1_year: "2021.01 – Present",
  work1_title: "Project Manager",
  work1_company: "Wuhan Ximing Technology Co., Ltd.",
  work1_desc: "Responsible for pre-sales consulting, requirement analysis, blueprint design, SOW formulation, and full lifecycle project management (pre-sales → implementation → operations). Led 10-18 person teams delivering integration and platform projects for manufacturing and government clients.",
  work2_year: "2017.04 – 2020.12",
  work2_title: "Implementation Consultant",
  work2_company: "Nanjing Bokesi AI Technology Co., Ltd.",
  work2_desc: "Drove large-scale SOE content management platform development, led cross-system integration and unified standards implementation. Expert in IBM ECM/IIB. Led ESB and iPaaS platform development.",
  work3_year: "2014.11 – 2017.03",
  work3_title: "Implementation Engineer",
  work3_company: "Kewosi (Beijing) Information Technology Co., Ltd.",
  work3_desc: "Built IBM Portal system for Shaanxi Coal, completed LDAP, WebSeal, TIM unified identity integration. Designed IBM Optim data masking solution for compliance and audit requirements.",

  // Projects (homepage cards) - only 3
  projects: "Project Experience",
  project_full: "View Full Project Details →",
  proj1_name: "HK Business Registration Optimization",
  proj1_org: "HK Companies Registry",
  proj1_period: "2025.05 – Present",
  proj1_role: "IT Project Manager",
  proj1_team: "5–8 People",
  proj1_budget: "¥900K",
  proj1_method: "Agile + Milestone Control",
  proj1_r1: "Page load 80% faster",
  proj1_r2: "Document upload 80% faster",
  proj1_r3: "Chinese compatibility 99%+",
  proj1_r4: "Successfully accepted",
  proj1_tags: "Java EE,IBM FileNet,Maven",
  proj2_name: "Smart Ward iPaaS Integration",
  proj2_org: "First Hospital of Jilin University",
  proj2_period: "2024.10 – 2025.04",
  proj2_role: "IT Project Manager",
  proj2_team: "5+ People",
  proj2_budget: "¥800K",
  proj2_method: "Waterfall Model",
  proj2_r1: "API development reduced 60%",
  proj2_r2: "Interaction efficiency up 40%",
  proj2_r3: "150K+ daily messages stable",
  proj2_r4: "First-pass acceptance",
  proj2_tags: "IBM ACE,MQ,NiFi,HL7,ELK",
  proj3_name: "Big Data Store Location Platform",
  proj3_org: "BMW China",
  proj3_period: "2021.04 – 2024.05",
  proj3_role: "IT Project Manager",
  proj3_team: "Cross-functional 20+",
  proj3_budget: "¥10M",
  proj3_method: "Agile + Milestone Control",
  proj3_r1: "Adopted into BMW China strategy",
  proj3_r2: "Data-driven location decisions",
  proj3_r3: "Coordinated 20+ cross-functional team",
  proj3_r4: "All 5 milestones delivered on time",
  proj3_tags: "Spark,PostGIS,Scikit-learn,Tableau",

  // Education & Certifications
  education: "Education & Certifications",
  edu_school: "Hubei Engineering University",
  edu_major: "Computer Science & Technology (Bachelor) 2011 – 2015",
  cert_pmp: "PMP Certification",
  cert_pmp_title: "PMI Project Management Professional",
  cert_filenet: "IBM FileNet Certified Professional",
  cert_filenet_title: "IBM Document Management Certification",
  cert_was: "IBM WebSphere App Server ND",
  cert_was_title: "IBM WebSphere Network Deployment Certification",

  // Projects page
  proj_page_title: "Project Experience",
  proj_page_subtitle: "Core project delivery details",
  proj_role: "Role",
  proj_team: "Team",
  proj_budget: "Budget",
  proj_method: "Management Model",
  proj_background: "Background",
  proj_analysis: "Requirements Analysis",
  proj_management: "Project Management",
  proj_collaboration: "Team Collaboration",
  proj_key_results: "Key Results",
  proj_architecture: "System Architecture",
  proj_tech_stack: "Tech Stack",

  // Project 1: HK Business Registry
  proj1_bg: "The business registration approval system had slow frontend loading (>30s per page), slow FileNet document uploads, and Chinese character display issues (garbled text and distortion) in FileNet's built-in text editor, affecting the image and compliance of the HK Companies Registry.",
  proj1_analysis: "Conducted thorough investigation of the issues, identified root causes, and reached out to partner vendors including WPS and FOXIT. Further explored requirements, set project boundaries, and compared vendor strengths to develop an alternative solution.",
  proj1_management: "Facilitated the HK Companies Registry's internal procurement process to ensure compliant project initiation. Managed development progress and risk control. Fully responsible for overall planning, resource coordination, risk identification, milestone reporting, and project acceptance.",
  proj1_collaboration: "The project involved the client team, our team, and product teams. Maintained proactive communication and coordination among all engineering teams.",
  proj1_stack: "Java EE,JavaScript,IBM FileNet,Maven,Chrome DevTools",

  // Project 2: Hospital iPaaS
  proj2_bg: "A Grade-3A hospital with 20+ systems (HIS, LIS, PACS, EMR) from different vendors, causing severe information silos.",
  proj2_analysis: "Conducted on-site clinical research, mapped the interface landscape of 20+ core systems, identified key business scenarios, and selected the iPaaS platform after evaluating multiple integration approaches.",
  proj2_management: "Adopted waterfall model with strict phase-gate progression. Created detailed interface development plans and integration schedules. Established interface testing checklists and rollback strategies.",
  proj2_collaboration: "Coordinated cross-vendor integration testing, organized user training, and established a tiered escalation mechanism (L1→L2→L3).",
  proj2_stack: "MQ,NiFi,Redis,HL7,ELK,Jaeger",

  // Project 3: BMW
  proj3_bg: "BMW China store expansion relied on experience-based decisions without data-driven scientific location analysis.",
  proj3_analysis: "Faced with numerous unclear requirements and inaccessible key stakeholders. Conducted stakeholder mapping analysis, broke through via multi-party coordination, converged requirements, and established communication mechanisms.",
  proj3_management: "Agile iteration + milestone control, decomposed into 5 milestones. Established risk register and strict cost control.",
  proj3_collaboration: "20+ cross-functional team with daily standups and weekly reports. Two-way training programs. Coordinated external data vendors.",
  proj3_stack: "Python,Apache Spark,Delta Lake,Scikit-learn,PostgreSQL,PostGIS,Hadoop,Airflow,Tableau",

  // Architecture labels
  arch_hospital_title: "Smart Ward iPaaS",
  arch_hospital_his: "HIS",
  arch_hospital_lis: "LIS",
  arch_hospital_pacs: "PACS",
  arch_hospital_emr: "EMR",
  arch_hospital_ace: "Nifi Integration",
  arch_hospital_ace_sub: "Protocol · Routing",
  arch_hospital_mq: "MQ Bus",
  arch_hospital_mq_sub: "150K/day · Zero Loss",

  arch_hk_title: "Approval System",
  arch_hk_frontend: "Frontend Opt",
  arch_hk_frontend_sub: "80% Faster",
  arch_hk_filenet: "FileNet",
  arch_hk_filenet_sub: "Doc Mgmt · Batch",

  // Project 4: GAC Honda
  proj4_name: "Enterprise iPaaS Platform Upgrade",
  proj4_org: "GAC Honda Automobile Co., Ltd.",
  proj4_period: "2023.07 – 2024.09",
  proj4_role: "IT Project Manager",
  proj4_team: "8–12 People",
  proj4_budget: "¥2M",
  proj4_method: "Agile Iteration",
  proj4_r1: "Integration efficiency up 40%",
  proj4_r2: "Downtime reduced 90%",
  proj4_r3: "MTTR significantly decreased",
  proj4_r4: "Platform stable for daily operations",
  proj4_tags: "IBM ACE,MQ,IBM GATEWAY,Kubernetes",
  proj4_bg: "Legacy ESB platform monolithic architecture bottleneck, lacking traffic governance, manual deployment, and insufficient availability for business growth.",
  proj4_analysis: "Investigated ESB platform pain points, identified three gaps: traffic governance, deployment process, and monitoring; aligned with client tech team on goals and priorities; selected APISIX+K8s containerization approach after evaluating multiple solutions.",
  proj4_management: "Decomposed into three phases: gateway governance, containerization migration, monitoring; established iteration reviews and milestone acceptance; designed rollback plans for business continuity.",
  proj4_collaboration: "Coordinated client ops, dev, and architecture teams; organized technical training and knowledge transfer; established escalation mechanisms.",
  proj4_stack: "IBM ACE,IBM MQ,IBM GATEWAY,Kubernetes/OpenShift,Redis,Prometheus,Grafana,Jenkins",

  // Project 5: ChinaBond
  proj5_name: "Enterprise Knowledge Base Cloud Platform",
  proj5_org: "China Bond Rating Co., Ltd.",
  proj5_period: "2018.01 – 2021.03",
  proj5_role: "Project Manager / Implementation Consultant",
  proj5_team: "6–10 People",
  proj5_budget: "¥1.5M",
  proj5_method: "Waterfall Model",
  proj5_r1: "Platform stable at 500+ QPS",
  proj5_r2: "Document search efficiency up 60%",
  proj5_r3: "Met financial compliance requirements",
  proj5_r4: "Established systematic knowledge management",
  proj5_tags: "IBM FileNet,CAS,LDAP,DB2",
  proj5_bg: "Financial institution's knowledge assets scattered across departments, lacking unified management and search capabilities, with strict financial data compliance and audit requirements.",
  proj5_analysis: "Surveyed knowledge management status across departments; mapped document lifecycle and permission requirements; designed unified knowledge base platform.",
  proj5_management: "Progressed through requirements→design→implementation→testing→launch phases; LoadRunner stress testing for performance validation; established go-live criteria.",
  proj5_collaboration: "Coordinated IT, business, and compliance departments; organized training to promote knowledge base adoption; wrote SOP documentation.",
  proj5_stack: "IBM FileNet,CAS,LDAP,Active Directory,LoadRunner,DB2,CTyun",

  // Architecture labels
  arch_gac_title: "iPaaS Upgrade Architecture",
  arch_gac_esb: "Legacy ESB",
  arch_gac_apisix: "IBM Gateway",
  arch_gac_apisix_sub: "Circuit Break · Rate Limit",
  arch_gac_k8s: "K8s Cluster",
  arch_gac_k8s_sub: "Blue-Green Deploy",
  arch_gac_monitor: "Prometheus + Grafana",
  arch_gac_monitor_sub: "Full-Stack Monitoring",

  arch_bond_title: "Knowledge Base Architecture",
  arch_bond_user: "Users",
  arch_bond_cas: "CAS / LDAP",
  arch_bond_cas_sub: "Unified Auth",
  arch_bond_filenet: "FileNet Doc Mgmt",
  arch_bond_filenet_sub: "Create→Review→Archive→Destroy",
  arch_bond_db: "DB2 + CTyun",

  arch_bmw_title: "Store Location Platform",
  arch_bmw_source: "Data Sources",
  arch_bmw_source_sub: "Population · Commercial · Traffic",
  arch_bmw_spark: "Spark Processing",
  arch_bmw_model: "Location Model",
  arch_bmw_model_sub: "H3 + ML",
  arch_bmw_tableau: "Tableau Dashboard",

  // Analysis page
  analysis_title: "Industry Insights",
  analysis_subtitle: "Project management, enterprise integration, and digital transformation trends",
  analysis_tech_trend: "📈 Technology Trends",
  analysis_chart_title: "Global iPaaS & Project Management Market Trends (2020-2025)",
  analysis_chart_ipaas: "iPaaS Market ($B)",
  analysis_chart_monitoring: "PM Market ($B)",
  analysis_arch_evo: "🔧 Architecture Evolution",
  analysis_arch_legacy_cloud: "ESB → iPaaS",
  analysis_arch_container: "Traditional → Containerized",
  analysis_arch_mono_micro: "Manual Ops → Automation",
  analysis_insights: "🔍 Industry Insights",
  analysis_takeaways: "💡 Key Takeaways",
  analysis_market_forecast: "📊 Market Forecast",
  analysis_market_billion: "$B",

  insight_integration_title: "iPaaS Integration",
  insight_integration_desc: "Enterprise integration evolves from ESB to cloud-native iPaaS. API gateways and event-driven architectures are mainstream.",
  insight_hospital_title: "Healthcare IT",
  insight_hospital_desc: "Smart wards and interoperability assessments drive hospital IS integration. 150K+ daily message processing is standard.",
  insight_observability_title: "Project Delivery",
  insight_observability_desc: "Full lifecycle management from requirements to acceptance. PMP methodology combined with agile practices ensures on-time, on-budget delivery.",
  insight_container_title: "Big Data Platform",
  insight_container_desc: "Spark, Delta Lake, and ML-driven analytics platforms become core decision-making tools. Data-driven scenarios like location analysis are maturing.",
  insight_automation_title: "AI Integration",
  insight_automation_desc: "AI/LLM technologies accelerate enterprise IT delivery. Prompt Engineering and AI solution design are becoming essential capabilities.",
  insight_middleware_title: "Enterprise Content Mgmt",
  insight_middleware_desc: "IBM FileNet and ECM platforms remain central to enterprise document management. Compliance, audit trails, and large-scale document processing are key capabilities.",

  trend_up: "↑ Growing",
  trend_stable: "→ Stable",

  takeaway1_title: "Requirements Analysis is Foundation",
  takeaway1_desc: "On-site research, precise stakeholder requirement identification, and proper project scoping are prerequisites for successful delivery.",
  takeaway2_title: "Cross-dept Coordination is Core",
  takeaway2_desc: "From client teams to product teams to external vendors, project managers must build efficient communication across all stakeholders.",
  takeaway3_title: "Risk Management Determines Success",
  takeaway3_desc: "Risk registers, rollback strategies, and escalation mechanisms enable proactive risk management rather than reactive firefighting.",
  takeaway4_title: "Delivery Quality is the Standard",
  takeaway4_desc: "Whether a 900K or 10M RMB project, final delivery quality and client satisfaction are the only measures of success.",

  market_ipaas: "2025 iPaaS Market",
  market_monitoring: "2025 PM Market",
  market_container: "2025 Digital Transformation",

  // Footer
  footer_contact: "Contact",
  footer_email: "Email",
};
