export const zh: Record<string, string> = {
  // Nav
  nav_home: "首页",
  nav_projects: "项目",
  nav_analysis: "行业洞察",

  // Hero
  name: "范坤",
  role_zh: "IT 项目经理 / PMP",
  role_en: "IT Project Manager / PMP",
  hero_intro: "资深 IT 项目交付管理，超 5 年系统集成与数字化转型经验，PMP 认证。专注企业级集成解决方案（iPaaS）、内容管理（ECM）、大数据项目交付，擅长全生命周期管理与跨部门协调。曾管理预算超 1000 万的企业级平台项目，领导 10-20 人团队，成功交付多个央企/外企项目。",
  email: "frank@hk-it.hk",
  twitter: "@frank4938",
  feishu: "飞书",

  // Counters
  years_experience: "年 IT 经验",
  projects_count: "核心项目",
  max_budget: "千万+ 最大预算",
  team_size: "人团队规模",

  // Skills
  skills: "专业技能",
  skills_ai: "AI 能力",
  skills_backend: "后端与中间件",
  skills_data: "数据与运维",
  radar_pm: "项目管理",
  radar_req: "需求分析",
  radar_arch: "技术架构",
  radar_lead: "团队领导",
  radar_risk: "风险管控",
  radar_cross: "跨部门协调",

  // Skill items
  skill_ai_llm: "AI/LLM 技术基础认知",
  skill_ai_poc: "AI 需求评估与 POC 验证",
  skill_ai_prompt: "Prompt Engineering",
  skill_ai_design: "AI 集成方案设计",
  skill_java: "Java EE / Spring Boot",
  skill_esql: "ESQL / IBM MQ (RDQM)",
  skill_ace: "IBM ACE / Apache NiFi",
  skill_apiconnect: "IBM API Connect",
  skill_oracle: "Oracle / PostgreSQL / DB2",
  skill_sqlserver: "SQL Server / Redis",
  skill_elk: "ELK + Jaeger",
  skill_prometheus: "Prometheus + Grafana",
  skill_docker: "Docker / Jenkins",

  // Work experience
  work_experience: "工作经历",
  work1_year: "2021.01 – 至今",
  work1_title: "项目经理",
  work1_company: "武汉汐鸣科技有限公司",
  work1_desc: "负责客户售前咨询、需求调研、蓝图设计、SOW制定及项目全生命周期管理（售前 → 实施 → 运维）。领导 10–18 人团队，成功交付多家制造业及政府客户的集成与平台项目。",
  work2_year: "2017.04 – 2020.12",
  work2_title: "开发实施顾问",
  work2_company: "南京宝科思人工智能科技有限公司",
  work2_desc: "推动大型国企内容管理平台建设，主导跨系统集成与统一标准落地，精通 IBM ECM/IIB 技术。主导企业服务总线（ESB）及 iPaaS 平台建设。",
  work3_year: "2014.11 – 2017.03",
  work3_title: "实施工程师",
  work3_company: "克沃斯（北京）信息技术有限公司",
  work3_desc: "负责陕煤化 IBM Portal 门户系统搭建，完成 LDAP、WebSeal、TIM 用户体系的统一集成。负责 IBM Optim 数据脱敏方案设计与开发。",

  // Projects (homepage cards) - only 3
  projects: "项目经验",
  project_full: "查看完整项目详情 →",
  proj1_name: "香港工商注册材料审批系统优化",
  proj1_org: "香港工商注册处",
  proj1_period: "2025.05 – 至今",
  proj1_role: "IT 项目经理",
  proj1_team: "5–8 人",
  proj1_budget: "¥90 万",
  proj1_method: "敏捷迭代 + 里程碑管控",
  proj1_r1: "页面加载提升 80%",
  proj1_r2: "文档上传提升 80%",
  proj1_r3: "中文兼容率达 99%+",
  proj1_r4: "项目顺利验收",
  proj1_tags: "Java EE,IBM FileNet,Maven",
  proj2_name: "智慧病房 iPaaS 集成",
  proj2_org: "吉林大学第一附属医院",
  proj2_period: "2024.10 – 2025.04",
  proj2_role: "IT 项目经理",
  proj2_team: "5+ 人",
  proj2_budget: "¥80 万",
  proj2_method: "瀑布模型",
  proj2_r1: "接口开发量减少 60%",
  proj2_r2: "交互效率提升 40%",
  proj2_r3: "日均 15 万+ 消息稳定运行",
  proj2_r4: "一次上线通过验收",
  proj2_tags: "IBM ACE,MQ,NiFi,HL7,ELK",
  proj3_name: "大数据门店选址平台搭建",
  proj3_org: "BMW",
  proj3_period: "2021.04 – 2024.05",
  proj3_role: "IT 项目经理",
  proj3_team: "跨职能 20+ 人",
  proj3_budget: "¥1000 万",
  proj3_method: "敏捷迭代 + 里程碑管控",
  proj3_r1: "纳入 BMW 中国市场战略框架",
  proj3_r2: "数据驱动选址决策",
  proj3_r3: "协调 20+ 人跨职能团队",
  proj3_r4: "5 个里程碑全部按期交付",
  proj3_tags: "Spark,PostGIS,Scikit-learn,Tableau",

  // Education & Certifications
  education: "教育背景 & 认证",
  edu_school: "湖北工程学院新技术学院",
  edu_major: "计算机科学与技术（本科）2011 – 2015",
  cert_pmp: "PMP 项目管理专业认证",
  cert_pmp_title: "PMI 项目管理协会认证",
  cert_filenet: "IBM FileNet Certified Professional",
  cert_filenet_title: "IBM 文档管理认证专家",
  cert_was: "IBM WebSphere Application Server ND",
  cert_was_title: "IBM 应用服务器网络部署认证",

  // Projects page
  proj_page_title: "项目经验",
  proj_page_subtitle: "核心项目交付详情",
  proj_role: "角色",
  proj_team: "团队",
  proj_budget: "预算",
  proj_method: "管理模式",
  proj_background: "项目背景",
  proj_analysis: "需求分析",
  proj_management: "项目管理",
  proj_collaboration: "团队协作",
  proj_key_results: "关键成果",
  proj_architecture: "系统架构",
  proj_tech_stack: "技术栈",

  // Project 1: HK Business Registry
  proj1_bg: "工商注册审批系统前端加载缓慢（页面加载超 30 秒），FileNet 文档上传耗时严重，FileNet 自带的文本编辑工具中文显示存在乱码与失真问题，影响香港工商注册处的形象以及内容的合规性。",
  proj1_analysis: "前期做了详细调研，了解了异常发生的情况，并根据问题找到我们合作的厂商，包括 WPS 和 FOXIT，进一步深挖需求，设置项目边界，然后结合边界对比厂商优势，制定替代方案。",
  proj1_management: "推动香港工商注册处推进内部招标流程，满足立项的合规合理，后续负责项目的开发进度的把控和风险把控，全面负责项目的整体规划、过程资源协调、风险识别、关键节点汇报、项目验收等工作。",
  proj1_collaboration: "项目涉及甲方团队，我们团队，以及产品团队，积极与多方工程师保持良好沟通协调。",
  proj1_stack: "Java EE,JavaScript,IBM FileNet,Maven,Chrome DevTools",

  // Project 2: Hospital iPaaS
  proj2_bg: "三甲医院院内 HIS、LIS、PACS、EMR 等 20+ 系统分属不同厂商，存在严重信息孤岛。",
  proj2_analysis: "深入临床一线调研，梳理医院 20+ 核心系统的接口现状；识别关键业务场景；评估多种集成方案后选定 iPaaS 平台。",
  proj2_management: "采用瀑布模型，严格按阶段推进；制定详细接口开发计划与联调排期；建立接口联调清单；设计回滚策略。",
  proj2_collaboration: "协调跨厂商联调；组织用户培训；建立问题升级机制（L1→L2→L3）。",
  proj2_stack: "IBM ACE,IBM MQ,NiFi,Redis,HL7,ELK,Jaeger",

  // Project 3: BMW
  proj3_bg: "BMW 中国门店拓展依赖传统经验判断，缺乏数据驱动的科学选址依据。",
  proj3_analysis: "面临大量不明确需求，核心干系人难以直接接触；干系人地图分析；多方协调突破；需求收敛；建立沟通机制。",
  proj3_management: "敏捷迭代+里程碑管控，拆解为 5 个里程碑；建立风险登记册；严格成本管控。",
  proj3_collaboration: "20+ 人跨职能团队；每日站会+周报；双向培训；协调外部数据供应商。",
  proj3_stack: "Python,Apache Spark,Delta Lake,Scikit-learn,PostgreSQL,PostGIS,Hadoop,Airflow,Tableau",

  // Architecture labels
  arch_hospital_title: "智慧病房 iPaaS 架构",
  arch_hospital_his: "HIS",
  arch_hospital_lis: "LIS",
  arch_hospital_pacs: "PACS",
  arch_hospital_emr: "EMR",
  arch_hospital_ace: "ACE 集成引擎",
  arch_hospital_ace_sub: "协议适配 · 智能路由",
  arch_hospital_mq: "MQ 消息总线",
  arch_hospital_mq_sub: "15万+/日 · 零丢失",

  arch_hk_title: "审批系统架构",
  arch_hk_frontend: "前端优化",
  arch_hk_frontend_sub: "加载提升 80%",
  arch_hk_filenet: "FileNet",
  arch_hk_filenet_sub: "文档管理 · 批量优化",

  // Project 4: GAC Honda
  proj4_name: "企业级 iPaaS 平台升级改造",
  proj4_org: "广汽本田汽车有限公司",
  proj4_period: "2023.07 – 2024.09",
  proj4_role: "IT 项目经理",
  proj4_team: "8–12 人",
  proj4_budget: "¥500 万",
  proj4_method: "敏捷迭代",
  proj4_r1: "集成效率提升 40%",
  proj4_r2: "宕机率降低 90%",
  proj4_r3: "MTTR 显著下降",
  proj4_r4: "平台稳定支撑日常运营",
  proj4_tags: "IBM ACE,MQ,APISIX,Kubernetes",
  proj4_bg: "原有 ESB 平台单体架构瓶颈凸显，缺乏流量治理能力，发布依赖人工操作，系统可用性无法满足业务增长需求。",
  proj4_analysis: "深入调研现有 ESB 平台痛点，识别流量治理、发布流程、监控能力三大短板；与甲方技术团队对齐改造目标与优先级；评估多种方案后选定 APISIX+K8s 容器化改造路线。",
  proj4_management: "拆解为网关治理、容器化迁移、监控建设三个阶段；建立迭代评审与里程碑验收机制；制定回滚方案保障业务连续性。",
  proj4_collaboration: "协调甲方运维、开发与架构团队；组织技术培训与知识转移；建立问题升级机制。",
  proj4_stack: "IBM ACE,IBM MQ,APISIX,Kubernetes/OpenShift,Redis,Prometheus,Grafana,Jenkins",

  // Project 5: ChinaBond
  proj5_name: "企业知识库云平台搭建",
  proj5_org: "中债资信评估有限责任公司",
  proj5_period: "2018.01 – 2021.03",
  proj5_role: "项目经理/实施顾问",
  proj5_team: "6–10 人",
  proj5_budget: "¥300 万",
  proj5_method: "瀑布模型",
  proj5_r1: "平台稳定运行支持 500+ QPS",
  proj5_r2: "文档检索效率提升 60%",
  proj5_r3: "满足金融合规要求",
  proj5_r4: "推动知识资产体系化运营",
  proj5_tags: "IBM FileNet,CAS,LDAP,Oracle",
  proj5_bg: "金融机构知识资产分散在各部门，缺乏统一管理与检索能力，且需满足金融行业数据合规与审计要求。",
  proj5_analysis: "调研各部门知识管理现状与痛点；梳理文档生命周期与权限体系需求；制定统一知识库平台方案。",
  proj5_management: "按需求→设计→实施→测试→上线阶段推进；通过 LoadRunner 压测确保性能达标；建立上线准入标准。",
  proj5_collaboration: "协调 IT、业务、合规多部门需求；组织培训推广知识库使用；编写 SOP 文档。",
  proj5_stack: "IBM FileNet,CAS,LDAP,Active Directory,LoadRunner,Oracle,VMware vSphere",

  // Architecture labels
  arch_gac_title: "iPaaS 升级架构",
  arch_gac_esb: "原有 ESB",
  arch_gac_apisix: "APISIX 网关",
  arch_gac_apisix_sub: "熔断 · 限流",
  arch_gac_k8s: "K8s 容器集群",
  arch_gac_k8s_sub: "蓝绿发布",
  arch_gac_monitor: "Prometheus + Grafana",
  arch_gac_monitor_sub: "全链路监控",

  arch_bond_title: "知识库平台架构",
  arch_bond_user: "用户",
  arch_bond_cas: "CAS / LDAP",
  arch_bond_cas_sub: "统一认证",
  arch_bond_filenet: "FileNet 文档管理",
  arch_bond_filenet_sub: "创建→审核→归档→销毁",
  arch_bond_db: "Oracle + vSphere",

  arch_bmw_title: "门店选址平台",
  arch_bmw_source: "数据源",
  arch_bmw_source_sub: "人口 · 商圈 · 交通",
  arch_bmw_spark: "Spark 处理",
  arch_bmw_model: "选址模型",
  arch_bmw_model_sub: "H3 + ML",
  arch_bmw_tableau: "Tableau 看板",

  // Analysis page
  analysis_title: "行业洞察",
  analysis_subtitle: "项目管理、企业集成、数字化转型相关行业动态",
  analysis_tech_trend: "📈 技术趋势分析",
  analysis_chart_title: "全球 iPaaS 与项目管理市场趋势（2020-2025）",
  analysis_chart_ipaas: "iPaaS 市场（亿美元）",
  analysis_chart_monitoring: "项目管理市场（亿美元）",
  analysis_arch_evo: "🔧 架构演进趋势",
  analysis_arch_legacy_cloud: "ESB → iPaaS",
  analysis_arch_container: "传统部署 → 容器化",
  analysis_arch_mono_micro: "手动运维 → 自动化",
  analysis_insights: "🔍 行业洞察",
  analysis_takeaways: "💡 核心观点",
  analysis_market_forecast: "📊 市场规模预测",
  analysis_market_billion: "亿美元",

  insight_integration_title: "iPaaS 集成",
  insight_integration_desc: "企业集成从传统 ESB 向云原生 iPaaS 演进，API 网关和事件驱动架构成为主流。协议适配、智能路由、灰度发布是关键技术能力。",
  insight_hospital_title: "医疗信息化",
  insight_hospital_desc: "智慧病房、互联互通评级推动医院信息系统集成需求，日均 15 万级消息处理成为常态。HL7 标准与 FHIR 加速医疗数据互通。",
  insight_observability_title: "项目交付管理",
  insight_observability_desc: "全生命周期管理从需求分析到验收交付，PMP 方法论结合敏捷实践，确保项目按时按质按预算完成。",
  insight_container_title: "大数据平台",
  insight_container_desc: "Spark、Delta Lake、机器学习驱动的数据分析平台成为企业决策的核心工具，数据驱动选址、预测等场景日益成熟。",
  insight_automation_title: "AI 集成",
  insight_automation_desc: "AI/LLM 技术加速融入企业 IT 交付流程，从需求分析辅助到智能运维，Prompt Engineering 和 AI 方案设计成为新能力要求。",
  insight_middleware_title: "企业内容管理",
  insight_middleware_desc: "IBM FileNet 等 ECM 平台在企业文档管理中仍占据核心地位，合规性、审计追踪、大规模文档处理是关键能力。",

  trend_up: "↑ 增长",
  trend_stable: "→ 稳定",

  takeaway1_title: "需求分析是项目基石",
  takeaway1_desc: "深入一线调研，精准识别干系人需求，设置合理项目边界，是项目成功交付的前提。",
  takeaway2_title: "跨部门协调是核心竞争力",
  takeaway2_desc: "从甲方团队到产品团队到外部供应商，项目管理者需要在不同利益相关方之间建立高效沟通机制。",
  takeaway3_title: "风险管理决定项目成败",
  takeaway3_desc: "建立风险登记册、设计回滚策略、制定问题升级机制，主动识别和应对风险而非被动救火。",
  takeaway4_title: "交付质量是唯一标准",
  takeaway4_desc: "无论是 90 万的小项目还是 1000 万的大平台，最终交付成果的质量和客户满意度才是衡量项目成功的标准。",

  market_ipaas: "2025年 iPaaS 市场",
  market_monitoring: "2025年项目管理市场",
  market_container: "2025年数字化转型市场",

  // Footer
  footer_contact: "联系方式",
  footer_email: "邮箱",
};
